name: Release Streamer iOS
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Check repo
        uses: actions/checkout@master
        with:
          repository: ${{ secrets.REPOSITORY}}
          token: ${{ secrets.TOKEN }}
          submodules: true

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
  
      - name: Bundle
        run: bundle install

      - name: Build
        env:
          FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 120
          FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
        run: bundle exec fastlane release_reslover

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Streamer-iOS.ipa
          path: Streamer-iOS.ipa
          if-no-files-found: error
